### ISSUE TITLE
Consider adding the app to the community list

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/Framaforms_ynh#1]
Hello !

This is a friendly notice from the Yunohost Apps team : our tool noticed that your app is pretty interesting but is not listed in the [community list](https://github.com/YunoHost/apps/blob/master/community.json) !

Please consider making a pull request to add it, such that people can easily learn about its existence from [this page](https://yunohost.org/#/apps). If you declare your app as working, you might also benefit from [automatic tests on the app C.I.](https://ci-apps.yunohost.org/).

It is relevant to add your app to the list even if it's not working or unmaintained since it might still help people who might want to continue packaging the app. Just be sure to correctly flag it as notworking/unmaintained.

Checkout the README to learn [how to add your app to the list](https://github.com/YunoHost/apps#how-to-add-your-app-to-the-community-list) (should take only a few minutes).

Datalove <3,

The YunoHost team

**Comment by Jibec** [comment]
this app doesn't work yet, and I'm unsure to have the time to finish it soon as better survey tools exists and are packaged, I'll probably destroy this repository.

**Comment by JimboJoe** [comment]
That would be sad to thrash the work you've done so far... What about the "inprogress" status?

**Comment by Jibec** [comment]
Maybe, not working, I'll do the PR as it looks important to you ;)

**Comment by alexAubin** [comment]
Closing the issue as the app is now in the community list ! Thanks !
