### ISSUE TITLE
captcha for creating a user from ".noho.st" address site is not working

### ISSUE THREAD

**Issue by dufoura** [YunoHost-Apps/framaforms_ynh#11]
Hi, 
I'm trying to use framaform on my server. My server is registered on a xxxx.noho.st domain.
The captcha 
Nom de ce site web (sans "www" ni ".org" Ex: "framapouet") - Name of this website (without "www" nor ".org", e.g. "framapouet")? *
don't recognize this domain, and an error happens each time I try to register. 
How can I fix it?
Thank you

**Comment by yalh76** [comment]
The application has been upgraded, can you retry and reopen this issue if needed.

**Comment by MayeulC** [comment]
This is a duplicate of #8 (the captcha is "framaforms")
