### ISSUE TITLE
Impossible to create a poll

### ISSUE THREAD

**Issue by webafrancois** [YunoHost-Apps/framaforms_ynh#21]
When I create a new user with the admin interface of framaforms, the user can't create a new empty poll or a new poll from a template :

> 
>  Page not found / Page introuvable
> La page que vous demandez n'a pas été trouvée. Désolé !
> 
> Si vous veniez pour remplir un formulaire, et que vous arrivez sur cette page, il est possible que la personne qui vous ait envoyé le lien vous ait communiqué une mauvaise adresse par erreur. N'hésitez pas à prendre contact avec elle.
> 

I think that the user don't have the good role. There are just 3 roles :
* auth user
* administrator
* translator 

If I put my user in administrator role, he can't yet create a poll.

**Comment by webafrancois** [comment]
The admin can't create forms either.

**Comment by Jaxom99** [comment]
I have the same issue on a fresh install, but it seems to be related to : https://github.com/YunoHost-Apps/framaforms_ynh/issues/10

Can you check and confirm this ?

**Comment by zamentur** [comment]
Should be fixed now
