### ISSUE TITLE
Error DRUPAL PDOException

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/framaforms_ynh#23]
_Yunohost version : 3.8.4.4 (stable)._

My instance is down, I have this message on the startpage :

`PDOException: could not find driver in lock_may_be_available() (line 167 of /var/www/framaforms/includes/lock.inc).`

**Comment by stemy2** [comment]
I have the exact same problem.

**Comment by zamentur** [comment]
Should be fixed now
