### ISSUE TITLE
Yunohost 3.6.4 - installation fails with Drush related error

### ISSUE THREAD

**Issue by decentral1se** [YunoHost-Apps/framaforms_ynh#4]
Here's my log:

> https://paste.yunohost.org/raw/ehorazalar

I can't see much from the logs to help ...

Ideas?

**Comment by decentral1se** [comment]
Strange, running `sudo -su postgres psql framaforms < framaforms.sq` works fine. However, it is the last thing seen in the log and looks like the cause of the error. Unclear how to trigger the same failure manually ...

**Comment by webafrancois** [comment]
Framaforms installation in Yunohost 3.7.1 works fine.
But the usage don't... 
But the install works.

Carefull, there a big security problem with the clear password in the log file (here with password=XXX) !!!
https://paste.yunohost.org/erarolekox.bash

Another issue...
