### ISSUE TITLE
Captcha requires writing "framaforms" for registration

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/framaforms_ynh#8]
> Nom de ce site web (sans "www" ni ".org" Ex: "framapouet") - Name of this website (without "www" nor ".org", e.g. "framapouet")? *

The answer seems to be hardcoded. I would like to see it become a setting at least, as this really isn't obvious when you host it elsewhere.

**Comment by yalh76** [comment]
The application has been upgraded, can you retry and reopen this issue if needed.

**Comment by MayeulC** [comment]
Yes, the bug is still present. I find closing these issues a tad rude, if I may :)

**Comment by yalh76** [comment]
Yes it seems its harcoded in the upstream app. Si if you want it to be changed, please open an issue at the upstream repository https://framagit.org/framasoft/framaforms

**Comment by MayeulC** [comment]
Hmm, I don't know much about the upstream app, and was about to open an issue upstream, but from a cursory search, it looks like this can be changed in the database, so it isn't really "hardcoded", right?

Line 55188 of framaforms.sql:

```sql
COPY public.riddler_questions (qid, question, answer) FROM stdin;
3       Nom de ce site web (sans "www" ni ".org" Ex: "framapouet") - Name of this website (without "www" nor ".org", e.g. "framapouet")?        framaforms
```

**Comment by yalh76** [comment]
That's means that could be directly changed in the database...

**Comment by gmilad** [comment]
(English translation below)

Bonjour,

Non pas besoin de changer dans la base de donnée, il suffit d'aller dans l'interface d'administration, puis Configuration-->Personnes-->CAPTCHA-->Riddler

Amicalement,
Gaëtan MAISON.

----------

English translation below
Good morning, sir,

No need to change in the database, just go to the administration interface, then Configuration-->People-->CAPTCHA-->Riddler

Friendly,
Gaëtan MAISON.
