### ISSUE TITLE
Guests cannot access forms

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/framaforms_ynh#9]
I was expecting guests to be able to answer a form without logging in:
> If no, only person with an account on your server will be able to create forms. In all cases, visitors will be able to reply to form

However, users are greeted with a yunohost sso page when I share the form link with them.

**Comment by nicolasVr** [comment]
Same problem for me.
Dans la configuration des rôles utilisateurs anonymes et authentifiés sont verrouillés et je ne sais pas quoi y faire.

**Comment by MayeulC** [comment]
@nicolasVr I ended up making a public instance and denying access to the /register page trough nginx's config.

**Comment by yalh76** [comment]
The application has been upgraded, can you retry and reopen this issue if needed.

**Comment by MayeulC** [comment]
Yes, the bug is still present. I find closing these issues a tad rude, if I may :)

**Comment by yalh76** [comment]
the app has to be installed in public and registrations are opened by default.
